[tool.poetry]
name = "cancel-culture"
version = "0.1.0"
description = ""
authors = ["Dikson Santos <diksonfer@gmail.com>"]
readme = "README.md"
packages = [{include = "cancel_culture"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
numpy = "^1.24.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
